### ISSUE TITLE
running example code...

### ISSUE THREAD

**Issue by gbmax** [karray/truepyxel#1]
Hello.
I am pleased to find your pyodide example, because I am not familiar with javascript and pyodide and there are little docs about pyodide with javascript.
I am trying to use pyodide to deploy keras model to mobile.
When testing your example, error occurs for some specific condition.
I inserted my code snippet into your example2 code.
```
from scipy.interpolate import splrep, splev

X = [1,2,3,4,5]
pixVal = [10, 20,30,40,50]
wl = [10, 30, 60, 90]

spl0 = splrep(pixVal, X, k=3)
X_spl1 = splev(wl, spl0)
```

When I test it many times(run script -> reload(F5) -> run -> reload ...), some times later it produces error as below image.
I tested in Windows 10.
I am not sure whether this bug is from pyodide or sample code incompleteness or another issue.
If this issue is settled, I would be very appreciative.
Thanks for good code example.

![2020-10-01 17_48_51-Pyodide example](https://user-images.githubusercontent.com/61690615/94788374-6d9d2300-040e-11eb-886a-04019da14f7d.png)

**Comment by karray** [comment]
Hi. I'm not sure what caused this error. My guess is that your WebAssembly container is out of memory. Sometimes I get the same error in my Chrome browser, so try the same code in Firefox or Edge.

You can also find more info about the error in Dev Console.

UPD: it seems this is a Chrome bug. You can read more [here](https://github.com/emscripten-core/emscripten/issues/5161)

**Comment by gbmax** [comment]
Thanks for information.
I traced the post you said, and it leads to chromium bug issue. 
Interestingly, it says the bug is fixed.. :)
(https://bugs.chromium.org/p/chromium/issues/detail?id=729768#c8)
So it seems like to give up using chrome browser.
Anyway, thanks a lot, I peeped another area I did not know.
